version: '3'
services:
  db:
    container_name: udemy-jobs-com-spring-batch-mysql-db
    image: mysql/mysql-server:8.0
    command: chmod +x /docker-entrypoint-initdb.d/root_privileges_manual.sh
#    command: "mysql -u root -p -A; root; update mysql.user set host='%' where user='root'; flush privileges; exit;"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_batch
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./scripts_sql/root_privileges_manual.sh:/docker-entrypoint-initdb.d/root_privileges_manual.sh